### ISSUE TITLE
添加插件报错 我的是jdk17.0.2 burp是v2021.10

### ISSUE THREAD

**Issue by h175h32** [smxiazi/xia_sql#7]
java.lang.ClassNotFoundException: burp.BurpExtender
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:445)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:587)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at java.base/java.lang.Class.forName0(Native Method)
	at java.base/java.lang.Class.forName(Class.java:467)
	at burp.rw.a(Unknown Source)
	at burp.rw.<init>(Unknown Source)
	at burp.fdd.a(Unknown Source)
	at burp.g03.lambda$panelLoaded$0(Unknown Source)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
为啥安装不上呢

**Comment by kingz40o** [comment]
应该是java版本的问题，你用你的java版本编译一个

**Comment by smxiazi** [comment]
我用jdk16编译了一个
https://pan.xj.hk/s/cd3be2
你试试可以用么

**Comment by h175h32** [comment]
> 我用jdk16编译了一个 https://pan.xj.hk/s/cd3be2 你试试可以用么

你这个就不报错了。

**Comment by smxiazi** [comment]
已把jdk16编译的上传到了下载那里了，后续需要可以直接下载了。
